### ISSUE TITLE
Checking out code

### ISSUE THREAD

**Issue by JayDotClass** [fadre/gravitySimulation#1]
Hello, I was wondering how to run this code?

I've been trying to run this code through VSCode but for some reason it doesn't recognise the main method you've put in Main.java. Any help?

Kind Regards,

Sando-K

**Comment by fadre** [comment]
I don't know what could be the issue with VS Code.
Easierst for running it is executing .`/gradlew run` in the top level directory.
Since its very old by now, it requires Java 8 to be the default java. Also you need a JDK with bundled JavaFX (so an oracle JDK, not AdoptOpenJDK with comes without java FX)

**Comment by JayDotClass** [comment]
Thank you so much for this! I honestly thought my chances of getting any response would be so slim. 

I cannot express how much this has helped me in my endeavours of making a Physical Sciences GUI Simulation.

I shall take this project to heart.

Kind Regards,

Sando-K

**Comment by fadre** [comment]
You're welcome :)
